### PR TITLE
Update dependencies to work with Capacitor v4

### PR DESCRIPTION
**Pull request by AndreaMinato**
Solves #4 

Updating the dependencies and peerDependencies is enough to make it work with Capacitor v4.

I tested it by creating a pkg with `npm pack` and using in an application I recently migrated to v4 from v3

### CODE REVIEW

**Comment by jkbz64** [comment]
Thanks for the pull request! 

I would also suspect the only thing that would need to be done would be to bump the dependencies because v4 was not really breaking but looking at other plugin commits I kind of think the android files would also need to be bumped just in case.
Random examples: [bluetooth-le](https://github.com/capacitor-community/bluetooth-le/commit/88f038aeed526c860cfb40e9a4cb9562c25d931b), [barcode-scanner](https://github.com/capacitor-community/barcode-scanner/commit/35772c5c3d56740678a6b4d98d129855b5b9b4bc), [sqlite](https://github.com/capacitor-community/sqlite/commit/67e324a551d900de7af4a25393edbd07d0dfabc5).

I think it would be fine to assume at least `android/build.gradle` and `android/gradle/wrapper/gradle-wrapper.properties` need to be bumped too. I couldn't find official info about migrating plugins to v4. Would be probably down to merge if these are bumped too

**Comment by jkbz64** [comment]
Okay, I found [this](https://github.com/rdlabo-team/capacitor-plugin-to-v4) tool. It seems to upgrade the remaining files correctly. I'm going to merge your commit and push the android-specific files. If you care please let me know if the plugin compiles/works after updating the android-specific files.

**Comment by AndreaMinato** [comment]
I tried installing it and it works fine.

I'm only using the `DataWedge.addListener("scan", (event)=>{})` function for my application

**Comment by jkbz64** [comment]
> I tried installing it and it works fine.
> 
> I'm only using the `DataWedge.addListener("scan", (event)=>{})` function for my application

Cool, just needed to know if it compiles properly, these changes should not affect the methods. 
Thanks for bringing the issue up and sending the PR.

**Pull request merged**
